server:
  port: 5000
spring:
  application:
    name: service-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://47.105.111.80:8761/eureka/

zuul:
  routes:
    business:
      path: /business/**
#      serviceId: business
    user-center:
      path: /user-center/**
#      serviceId: user-center