

spring:
  application:
    name: busiess
  profiles:
    active: default
  jackson:
    default-property-inclusion: non_null

  cloud:
    config:
    enabled: true

eureka:
  instance:
  preferIpAdddress: true
  client:
    registryWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://47.105.111.80:8761/eureka/

#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000

server:
  port: 8082

